version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.7-node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: "SHA256:/3QWVENLRNeLfLsRlwwihLejyRAmGQRoXfkOUIYPZ+4"
      - run: bash deploy.bash

  rubocop:
    docker:
      - image: cimg/ruby:3.2.7-node
        environment:
          RAILS_ENV: development
    steps:
      - checkout
      - run:
          name: install rubocop
          command: |
            gem install rubocop
      - run: rubocop

workflows:
  version: 2
  build:
    jobs:
      - build
      - rubocop
