version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-jessie
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: "fb:d7:d6:b6:c5:8b:1f:0e:96:0b:d9:0d:be:f8:00:49"
      - run: bash deploy.bash
